### ISSUE TITLE
cfmongodb not found after reinit 

### ISSUE THREAD

**Issue by Tropicalista** [jclausen/cbmongodb#1]
I'm using this module and after each reinit it throws an error of 

```
invalid component definition, can't find component [cfmongodb.core.MongoClient]
```

Adding this 

```
this.mappings[ "/cfmongodb" ] = COLDBOX_APP_ROOT_PATH & "modules/cbmongodb/modules/cfmongodb";
```

to application.cfc solved the problem. Probably should be added in readme.

**Comment by jclausen** [comment]
Hmm.  That shouldn't be an issue as the ModuleConfig.cfc for cfmongodb has its own mapping key.   Thanks for the heads-up.  I'll check in to why it's not registering in the correct order. Which version of Coldbox are you running and did you install the module through  Commandbox?

**Comment by Tropicalista** [comment]
I'm installing through commandbox and I'm on ColdBox 4.1.0.

**Comment by jclausen** [comment]
The latest commit up to the upstream cfmongodb module should fix this issue and remove the requirement for the Application.cfc mapping.  

On a related note, the development branch currently de-couples the cfmongodb library completely and uses the 3.0+ Java drivers directly.  I've still got some work to do in cleaning up the code smells left over integration, but it's a nice improvement and will be a lot more lightweight.
