### ISSUE TITLE
3.4 upgrade

### ISSUE THREAD

**Issue by pjacekm** [jclausen/cbmongodb#22]
Hi Jon, any plans for upgrading the driver to 3.4?

**Comment by jclausen** [comment]
Hi @pjacekm :  Thanks for your submission. I will get that updated this weekend.

**Comment by pjacekm** [comment]
Hi @jclausen , just checking in, any progress on this issue?

**Comment by jclausen** [comment]
@pjacekm : The driver has been updated in the latest development branch to 3.5.0.  I've got a few other tickets to close and then I'll bump a new master release.  For now, `box install cbomongodb@be` will install the version with 3.5.0 (after this Travis build is done : https://travis-ci.org/jclausen/cbmongodb/jobs/309002628 )  Sorry for the delay on this. I've been swamped with other projects.
