### ISSUE TITLE
IN not supported in where?

### ISSUE THREAD

**Issue by sdwebguy** [jclausen/cbmongodb#25]
On the bottom of 
https://github.com/jclausen/cbmongodb/wiki/2C.-Loading-and-Querying-Documents

it says 
`Valid operators currently include "=","!=","<",">",">=","<=","IN" and "Exists"`

which should map IN  to $in   but I dont see that working anywhere. 

ActiveEntity shows the valid operators are:
```
this.set_operators([
			'=',
			'!=',
			'>=',
			'<=',
			'<>',
			'like'
		]);
```

Is there a way to use IN or is that a documentation error?

**Comment by sdwebguy** [comment]
I added IN to the set_operators and then in ActiveEntity.cfc where() added a case for it. Works now.

**Comment by jclausen** [comment]
Can you pull request your changes? I believe these were intended to be supported at one point, but were backed out due to query errors.

**Comment by sdwebguy** [comment]
@jclausen Sure.. just issued https://github.com/jclausen/cbmongodb/pull/26
